### ISSUE TITLE
Create a home page 

### ISSUE THREAD

**Issue by simonmeggle** [Robotmk/robotmk.org#1]
As already discussed on Upwork, I need a replacement for the landing page of robotmk which was on Thinkific. 
As a very first starting point, I would like to ask you if you could reproduce something like the page which I showed you as screenshot. 

![image](https://github.com/Robotmk/robotmk.org/assets/1897410/97d5bb55-86ba-481e-b02b-9ced42504e27)

It's completely enough if you provide the skeleton an I will care for the content. 

- hero section will have another image; I will create one. Text will be similar. 
- A feature listing as in the original page would be cool again (see [archive.org](https://web.archive.org/web/20240110155452/https://www.robotmk.org/))
  - Big icon 
  - Text provided by me
- The page is i18ned, prepare the english one, I can do the german one

Are these specs enough so that you can start to create such a home page?

**Comment by ccthecode** [comment]
Yes I can work with this.

**Comment by ccthecode** [comment]
So that means. I am replacing what is here with the new homepage design above?
<img width="1278" alt="image" src="https://github.com/Robotmk/robotmk.org/assets/62962271/ab2c1282-cfea-4d0f-abd6-b7e37a134171">

**Comment by simonmeggle** [comment]
Yes, exactly. "HOME" should not show the current page anymore, but the new home page. 
If you have any further ideas for design or improvemts, please let me know. I am completely open.   😃 Thanks!

**Comment by ccthecode** [comment]
Sure! No Idea now. But I'll let you know if something comes up

**Comment by simonmeggle** [comment]
One question, Williams.... do you think we have a first version of the landing page next week? 
I am asking because then the Checkmk Conference happens in Munich. Chances are that more people are visiting the page then.

**Comment by ccthecode** [comment]
Yes, that's very possible.

**Comment by ccthecode** [comment]
please can you send me your Calendly embed code and point me to the documentation

**Comment by simonmeggle** [comment]
Hi Williams, thats not needed on the home page. This is a tool called Brevo; the booking form is already embedded into https://www.robotmk.org/en/professionalsupport/.

**Comment by ccthecode** [comment]
Got it!

Please can you checkout to the "homepage-development" branch and let me know if want any other sections removed.

https://github.com/Robotmk/robotmk.org/tree/homepage-development

**Comment by ccthecode** [comment]
What was here (box) ?

<img width="867" alt="image" src="https://github.com/Robotmk/robotmk.org/assets/62962271/c9ec1b6b-8831-41bc-a604-695dc5ccb0d7">

**Comment by ccthecode** [comment]
You can start editing the Deutsche content in 
1. `content\_index.de.md`
2. i18n\de.yaml from [line 66 - 73](https://github.com/Robotmk/robotmk.org/blob/9df77f0723f5cb2226f2baea7cbfafb3ecac6345/i18n/de.yaml#L65): (#prefooter home)
3. hugo.yaml: line [72 - 111](https://github.com/Robotmk/robotmk.org/blob/9df77f0723f5cb2226f2baea7cbfafb3ecac6345/hugo.yaml#L71)

**Comment by simonmeggle** [comment]
Hi Williams, reviewed it, thanks. 
Perhaps my specs were not precise enough, but please see the mockup screenshot above - I would like to have the header/footer **from my current page.** 
![CleanShot 2024-06-12 at 05 41 42](https://github.com/Robotmk/robotmk.org/assets/1897410/dff60f2c-cafc-4f18-b1ca-0f02c715f945)

Does that make sense? Could you fix that please?

**Comment by ccthecode** [comment]
I apologize, actually it was my fault. I missed that. 

I'd incorporate that, not a problem.

**Comment by ccthecode** [comment]
I have added the nav menu. You can check now. Updating footer soon

EDIT: Footer is added now

**Comment by simonmeggle** [comment]
Hi Williams, the new home page looks cool. I did not think that you can replicate the original page that much. Very cool. Thanks!

**Comment by simonmeggle** [comment]
One thing: the font in the navigation bar is different from the other ones. 
Is there any chance to fix that? 

![CleanShot 2024-06-19 at 16 05 53](https://github.com/Robotmk/robotmk.org/assets/1897410/be914d40-c18d-4564-b549-2d36548bb8e1)

**Comment by ccthecode** [comment]
Alright, I'll look into

**Comment by ccthecode** [comment]
[Done](https://github.com/Robotmk/robotmk.org/commit/73d38d2eab9d9b94521631fbb6dc53797a04be1b). I assume you prefer the font used in the Blog for the homepage. Let me know if you need it the other way

**Comment by simonmeggle** [comment]
Font looks good 👍  Thanks. 
It seems that the hugo.yaml contains a lot of menu config lines which are not needed anymore. Could you tidy them up please?

**Comment by ccthecode** [comment]
Alright. I'll do that

**Comment by ccthecode** [comment]
FIXED: https://github.com/Robotmk/robotmk.org/tree/sanitize-hugo-config

**Comment by simonmeggle** [comment]
Thanks Williams!
