### ISSUE TITLE
Menu item stays activated

### ISSUE THREAD

**Issue by simonmeggle** [Robotmk/robotmk.org#2]
I saw this glitch very early but never cared. 
Perhaps you can inspect where this is coming from and fix it right away? 
Thanks!

![CleanShot 2024-06-19 at 16 01 24](https://github.com/Robotmk/robotmk.org/assets/1897410/f13b286b-ddcb-46c3-92c3-85ec12dd86fd)

**Comment by ccthecode** [comment]
I'll do

**Comment by ccthecode** [comment]
Fixed: https://github.com/Robotmk/robotmk.org/tree/homepage-development

From what I see the logic is technically correct just that we are not fulfilling the intent behind the logic. 
The 'menu-active' class persists for sub pages within a section. 
In this case, "getting started" is a sub page within the blog section. So its only right for it to highlight both pages.

I have rewritten the logic to account for such edge case. But you **must update** this [array](https://github.com/Robotmk/robotmk.org/blob/b3a1cbfa9760b8a1c7b80424919d39daae11d955/hugo.yaml#L116) with the page in question and it's multilingual counterpart

**Comment by simonmeggle** [comment]
Awesome work! (I am again impressed by your debugging skills! 👍 )

**Comment by ccthecode** [comment]
I appreciate your kind words!
